[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common 	= { path = "../common" }

math 	= { path = "../../libs/math" }
net 	= { path = "../../libs/net" }

log = "*"
noise = "*"
raw-window-handle = "*"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { path = "../../libs/windows" }

[target.'cfg(target_os = "linux")'.dependencies]
x11 	= { path = "../../libs/x11" }
